(function () {
    'use strict';

    /*
     * ============================================================
     * Legacy Art Mods Compat (Plus)
     * ============================================================
     *
     * 本模組分成兩類兼容規則：
     *
     * 1. 官方歷史命名差異
     *    → Modern → Legacy Candidate Generator
     *    → 用來取代早期龐大的 SPECIAL_RENAMES / PATTERN_RENAMES
     *    → 普通情況一律保持 Native Modern 優先
     *
     * 2. 額外 / 第三方特殊兼容
     *    → EXTRA_COMPAT_RULES
     *    → 保留各自的特殊優先級與語義
     *    → 例如牛耳 before-native、AU 面擴 after-native
     *
     * Runtime 順序：
     *   Phase 0    特殊 before-native
     *   Phase 0.5  Legacy clothes gray（可染色舊素材優先）
     *   Phase 1    Native Modern
     *   Phase 2    特殊 after-native
     *   Phase 3    其餘官方 Legacy Candidates
     *
     * 本模組不修改 BSA imgListRef，也不依賴 boot.json.compat。
     * ============================================================
     */

    const TARGET_MOD = '旧版图片名称适配';
    const DEBUG = true;
    const DEBUG_FILTER = '';
    const debugHistory = [];

    /*
     * 基礎 Debug logger。
     * 圖片 Request 本身使用後面的聚合 Trace，避免逐條 TRY 洗版。
     */
    function compatLog(type, ...args) {
        if (!DEBUG) return;
        const text = args.join(' ');
        if (DEBUG_FILTER && !text.toLowerCase().includes(DEBUG_FILTER.toLowerCase())) return;
        if (debugHistory.length >= 300) debugHistory.shift();
        debugHistory.push({ time: performance.now(), type, args: [...args] });
        console.log(`[${TARGET_MOD}][${type}]`, ...args);
    }

    /*
     * ============================================================
     * Path Helpers
     * ============================================================
     */

    /**
     * 將外部路徑統一成內部規則使用的相對格式。
     * 例如 img/clothes/... → clothes/...。
     */
    function cleanPath(p) {
        if (!p) return '';
        let t = String(p).replace(/\\\\/g, '/').replace(/^\.\//, '').replace(/^\//, '');
        if (t.startsWith('img/')) t = t.slice(4);
        return t;
    }

    /** Candidate 去重 helper。 */
    function unique(list) {
        return [...new Set(list.filter(Boolean))];
    }

    /** 將路徑拆成 dir / file / base / ext，供各規則共用。 */
    function splitFile(path) {
        const slash = path.lastIndexOf('/');
        const dir = slash >= 0 ? path.slice(0, slash + 1) : '';
        const file = slash >= 0 ? path.slice(slash + 1) : path;
        const dot = file.lastIndexOf('.');
        return {
            dir,
            file,
            base: dot >= 0 ? file.slice(0, dot) : file,
            ext: dot >= 0 ? file.slice(dot) : ''
        };
    }

    /**
     * 追加舊版常見的 gray / non-gray 候選。
     *
     * 必須保持冪等：已是 *_gray.png 時不能再生成 *_gray_gray.png。
     */
    function addGrayVariants(out, path) {
        if (!path || !/\.png$/i.test(path)) return;
       
        if (/_gray\.png$/i.test(path)) {
            out.push(path);
            out.push(path.replace(/_gray\.png$/i, '.png'));
            return;
        }

        out.push(path.replace(/\.png$/i, '_gray.png'));
        out.push(path);
    }

    /*
     * ============================================================
     * Official Legacy Mapping Exceptions
     * ============================================================
     *
     * EXACT 只保留無法可靠抽象成通用規則的一對一特殊映射。
     *
     * 格式：
     *   'Modern path': 'Legacy path'
     *
     * 範例：
     *   'ui/clothes/traits/face-covering.png':
     *       'ui/clothes/traits/covered.png'
     *
     * 能規則化的歷史差異應放到各 Candidate Generator，
     * 不要重新把 EXACT 膨脹成大型映射表。
     *
     * 若只有少量特殊案例，或無法確認規則是否普遍成立，
     * 寧可保留為 EXACT，避免過度泛化。
     *
     * 需要 before-native / after-native 等特殊優先級的案例，
     * 應放入 EXTRA_COMPAT_RULES，而不是 EXACT。
     * ============================================================
     */

    // Only true semantic exceptions stay as data. Everything else is generated by rules below.
    const EXACT = new Map(Object.entries({
        'ui/clothes/traits/face-covering.png': 'ui/clothes/traits/covered.png',
        'body/parasites/urchin-clit.png': 'body/cliturchin.png',
        'body/parasites/slime-clit.png': 'body/clitslime.png',
        'body/parasites/urchin-tummy.png': 'body/tummyurchin.png',
        'body/parasites/slime-tummy.png': 'body/tummyslime.png',
        'body/ear-slime-panties.png': 'body/parasitepanty.png',
        'body/ear-slime-shorts.png': 'body/parasiteshorts.png',
        'body/ear-slime-chastity-0.png': 'clothes/genitals/slimechastitycage/frayed-1.png',
        'body/ear-slime-chastity-1.png': 'clothes/genitals/slimechastitycage/full0.png',
        'body/ear-slime-chastity-2.png': 'clothes/genitals/slimechastitycage/full1.png',
        'body/ear-slime-chastity-3.png': 'clothes/genitals/slimechastitycage/full2.png',
        'clothes/hands/belted/right-cover-belts.png': 'clothes/hands/belted/left_cover_belts_gray.png',
        'clothes/hands/belted/right-idle-belts.png': 'clothes/hands/belted/right_cover_belts_gray.png',
        'clothes/hands/belted/left-cover-belts.png': 'clothes/hands/belted/hold_belts_gray.png',
        'clothes/hands/belted/right-hold-belts.png': 'clothes/hands/belted/right_belts_gray.png',
        'clothes/props/general/shoebox.png': 'clothes/props/general/shoe-box.png',
        'clothes/props/tending/hawk-egg-1.png': 'clothes/props/tending/hawk-egg.png',
        'ui/tf-fallen-angel.png': 'ui/tf_fallenangel.png',
        'clothes/lower/open skort/acc-full.png': 'clothes/lower/open skort/acc_frayed_gray.png',
        'clothes/lower/open skort/acc-torn.png': 'clothes/lower/open skort/acc_tattered_gray.png',
        'clothes/handheld/parasolpaper/right-hold-apricots-acc.png': 'clothes/handheld/parasolpaper/right-hold-acc.png',
        'clothes/belly/belly-mask-upper-shadow-2.png': 'clothes/belly/belly_mask_upper_shadow.png',
        'clothes/belly/belly-mask-upper-shadow.png': 'clothes/belly/belly_mask_upper_shadow_2.png',
        'clothes/upper/winterjacket/left-cover-acc.png': 'clothes/upper/winterjacket/left_acc_gray.png',
        'clothes/upper/winterjacket/left-idle-acc.png': 'clothes/upper/winterjacket/left_cover_acc_gray.png',
        'clothes/under-upper/harnessbra/4-acc.png': 'clothes/under-upper/harnessbra/4-accl.png',
        'clothes/under-lower/harness panties/acc.png': 'clothes/under-lower/harness panties/frayed-metal.png',
        'ui/clothes/small-arrow.png': 'ui/clothes/small_uarrow.png',
        'misc/icon/wrench.png': 'ui/wrench.png',
        'ui/pepper-spray-empty.png': 'ui/emptyspray.png',
        'ui/sidebar-closed.png': 'ui/icon_closed.png',
        'ui/sidebar-day.png': 'ui/icon_day.png',
        'ui/sidebar-open.png': 'ui/icon_open.png',
        'ui/pepper-spray.png': 'ui/pepperspray.png',
        'ui/weather/thermo-filled.png': 'ui/weather/thermo_filled.png',
        'clothes/handheld/pompoms/right-hold-acc.png': 'clothes/handheld/pompoms/hold_acc_gray.png',
        'clothes/props/npc/witchprisoner/hair-braid-challenge-faithblooms.png': 'clothes/props/npc/witchprisoner/hair_braid_challenge_faithBlooms.png',
        'clothes/props/npc/witchprisoner/hair-clean-challenge-faithblooms.png': 'clothes/props/npc/witchprisoner/hair_clean_challenge_faithBlooms.png',
        'clothes/props/npc/witchprisoner/hair-dirty-challenge-faithblooms.png': 'clothes/props/npc/witchprisoner/hair_dirty_challenge_faithBlooms.png',
        'clothes/props/npc/witchprisoner/hair-flowers-challenge-faithblooms.png': 'clothes/props/npc/witchprisoner/hair_flowers_challenge_faithBlooms.png',
        'clothes/upper/jumpsuit/shoes.png': 'clothes/upper/jumpsuit/Shoes.png'
    }));

    /*
     * 少數 handheld 在舊版的 hold / cover / acc 語義不同，
     * 因此用小型 Set 保留真正的歷史例外。
     */
    const HANDHELD_SWAP_DIRS = new Set(['candy cane', 'cane', 'crutch']);
    const HANDHELD_ARM_DIRS = new Set(['pompoms']);
    const HANDHELD_ACC_SWAP_DIRS = new Set(['backpack', 'star purse']);

    /*
     * ============================================================
     * Official Legacy Candidate Generators
     * ============================================================
     *
     * 這一區只負責官方版本歷史命名差異。
     * 第三方特殊規則與特殊優先級請放 EXTRA_COMPAT_RULES。
     * ============================================================
     */

    /**
     * Body / breasts / cum / parasite / penis / pregnancy / mannequin
     * 等主體資源的 Modern → Legacy 候選。
     */
    function bodyCandidates(path) {
        if (!path.startsWith('body/')) return [];
        const out = [];

        if (path === 'body/base-head.png') out.push('body/basehead.png');
        let m = path.match(/^body\/base-(classic|curvy|slender|soft)\.png$/);
        if (m) out.push(`body/basenoarms-${m[1]}.png`);

        m = path.match(/^body\/(left|right)-arm-(idle|cover|hold)(.*)\.png$/);
        if (m) {
            const tail = m[3] || '';
            out.push(`body/${m[1]}arm${m[2]}${tail}.png`);
            if (tail.includes('-')) out.push(`body/${m[1]}arm${m[2]}${tail.replace(/-/g, '_')}.png`);
        }
        if (path === 'body/scars-wraith.png') out.push('body/wraith_scars.png');

        m = path.match(/^body\/breasts\/breasts-(\d+)\.png$/);
        if (m) out.push(`body/breasts/breasts${m[1]}.png`);
        m = path.match(/^body\/breasts\/clothed-(\d+)\.png$/);
        if (m) out.push(`body/breasts/breasts${m[1]}_clothed.png`);
        m = path.match(/^body\/breasts\/ear-slime-(\d+)\.png$/);
        if (m) out.push(`body/breasts/breastsparasite${m[1]}.png`);
        m = path.match(/^body\/breasts\/slime-(\d+)\.png$/);
        if (m) out.push(`body/breasts/chestslime${m[1]}.png`);
        m = path.match(/^body\/breasts\/urchin-(\d+)\.png$/);
        if (m) out.push(`body/breasts/chestparasite${m[1]}.png`);
        if (path === 'body/breasts/mask-curvy.png') out.push('body/breasts/breasts-curvy.png');
        if (path === 'body/breasts/mask-curvy-3-4.png') out.push('body/breasts/breasts-curvy-mid.png');
        if (path === 'body/breasts/mask-slender.png') out.push('body/breasts/breasts-slender.png');
        if (path === 'body/breasts/mask-slender-3-4.png') out.push('body/breasts/breasts-slender-mid.png');

        const drip = path.match(/^body\/cum\/(vaginal|anal|mouth)-(start|very-slow|slow|fast|very-fast)\.png$/);
        if (drip) {
            const a = drip[1][0].toUpperCase() + drip[1].slice(1);
            const speed = { 'start':'Start', 'very-slow':'VerySlow', 'slow':'Slow', 'fast':'Fast', 'very-fast':'VeryFast' }[drip[2]];
            out.push(`body/cum/${a}CumDrip${speed}.png`);
        }
        const cumReverse = {
            'chest-4':'Chest 4,5', 'face-1':'Face 1,2', 'face-2':'Face 3,4', 'face-3':'Face 5',
            'feet-1':'Feet 2,3', 'feet-2':'Feet 4,5', 'neck-1':'Neck 1,2', 'neck-2':'Neck 3,4', 'neck-3':'Neck 5',
            'left-arm-1':'Left Arm 1,2,3', 'left-arm-2':'Left Arm 4,5',
            'right-arm-1':'Right Arm 1,2,3', 'right-arm-2':'Right Arm 4,5'
        };
        m = path.match(/^body\/cum\/([^/]+)\.png$/);
        if (m) {
            if (cumReverse[m[1]]) out.push(`body/cum/${cumReverse[m[1]]}.png`);
            let n = m[1].match(/^(chest|thighs|tummy)-(\d+)$/);
            if (n) out.push(`body/cum/${n[1][0].toUpperCase()+n[1].slice(1)} ${n[2]}.png`);
        }

        m = path.match(/^body\/parasites\/(slime|urchin)-cage(?:-(fetish|flat|small))?\.png$/);
        if (m) {
            const dir = m[2] === 'fetish' ? 'chastitycagefetish' : m[2] === 'flat' ? 'flatchastitycage' : m[2] === 'small' ? 'smallchastitycage' : 'chastitycage';
            out.push(`clothes/genitals/${dir}/${m[1]}.png`);
        }
        m = path.match(/^body\/parasites\/(slime|urchin)-(?:hard|soft)-(\d+)\.png$/);
        if (m) {
            const n = Number(m[2]) - 2;
            out.push(`body/penis/penis${m[1]}${n}.png`);
        }
        m = path.match(/^body\/(penis|penis-no-balls)\/(hard|soft|hard-virgin|soft-virgin|condom-hard|condom-soft|ear-slime)-(\d+)\.png$/);
        if (m) {
            const oldN = Number(m[3]) - 2;
            const n = String(oldN);
            const dir = m[1] === 'penis-no-balls' ? 'penisnoballs' : 'penis';
            const fam = m[2];
            if (fam === 'hard' || fam === 'soft') out.push(`body/${dir}/penis${n}.png`);
            if (fam === 'hard-virgin' || fam === 'soft-virgin') out.push(`body/${dir}/penis_virgin${n}.png`);
            if (fam === 'condom-hard' || fam === 'condom-soft') out.push(`body/${dir}/condom${n}.png`);
            if (fam === 'ear-slime') {
                // Historical parasite images lived under body/penis even for the no-balls modern branch.
                out.push(`body/penis/penisparasite${n}.png`);
                if (m[1] === 'penis') out.push(`body/penis/penisparasiteballs${n}.png`);
            }
        }
        if (path === 'body/penis/chastity.png') {
            out.push('body/penis/penis_chastity.png', 'body/penis/penis_chastityflat.png', 'body/penis/penis_chastitysmall.png');
        }

        m = path.match(/^body\/(?:preggy-belly|pregnant-belly)\/(\d+)\.png$/);
        if (m) {
            out.push(`body/preggyBelly/pregnancy_belly_${m[1]}.png`);
            out.push(`body/preggyBelly/pregnant${Number(m[1]) + 1}.png`);
        }

        if (path.startsWith('body/mannequin/')) {
            const q = path.replace(/^body\/mannequin\//, '');
            if (q === 'base-body.png') out.push('body/mannequin/basenoarms.png');
            if (q === 'base-head.png') out.push('body/mannequin/basehead.png');
            let a = q.match(/^(left|right)-arm-(idle|cover|hold)\.png$/);
            if (a) out.push(`body/mannequin/${a[1]}arm${a[2]}.png`);
            let b = q.match(/^breasts\/breasts-(\d+)\.png$/);
            if (b) out.push(`body/mannequin/breasts/breasts${b[1]}.png`);
            b = q.match(/^breasts\/clothed-(\d+)\.png$/);
            if (b) out.push(`body/mannequin/breasts/breasts${b[1]}_clothed.png`);
        }

        return out;
    }

    /**
     * Bodywriting 官方歷史命名候選。
     * 舊版大量使用 underscore，新版部分名稱改用 hyphen。
     */
    function bodywritingCandidates(path) {
        if (!path.startsWith('bodywriting/')) return [];
        const out = [];
        // 0.5.8 bodywriting used underscores in both variable folders and body-part filenames.
        if (path.includes('-')) out.push(path.replace(/-/g, '_'));
        const m = path.match(/^(.*?)([a-z])-([0-9]+)([^/]*)\.png$/i);
        if (m) out.push(`${m[1]}${m[2]}${m[3]}${m[4].replace(/-/g, '_')}.png`);
        return out;
    }

    /**
     * Clothes 官方歷史命名候選。
     *
     * 主要處理 slot / variant / arm state / handheld state / acc / gray，
     * 以及舊版省略 idle / primary 等常見命名差異。
     *
     * 此函數只產生候選，不決定最終使用哪張圖；Runtime 仍會依
     * 優先順序實際 probe，因此普通官方規則不會覆蓋 Native Modern。
     */
    function clothesCandidates(path) {
        if (!path.startsWith('clothes/')) return [];
        const out = [];
        const parts = path.split('/');
        if (parts.length < 4) return out;
        const slot = parts[1];
        const dirVar = parts[2];
        const filename = parts.slice(3).join('/');
        const f = splitFile(filename);
        let core = f.base;
        const ext = f.ext || '.png';

        const oldSlot = slot.replace(/-/g, '_');
        let oldVar = dirVar;
        if (dirVar === 'sheer lace pyjama') oldVar = 'sheer lace pajama';
        if (dirVar === 'fishnet garter stockings') oldVar = 'harness garter and fishnet stockings';
        if (dirVar === 'striped garter stockings') oldVar = 'harness garter and striped stockings';
        if (slot === 'under-upper' && dirVar === 'swimshirt') {
            parts[1] = 'upper';
        }

        const prefixes = [`clothes/${parts[1].replace(/-/g, '_')}/${oldVar}/` + f.dir];
        // Some 0.5.8 packs already used under_upper for swimshirt while others used upper. Try both.
        if (slot === 'under-upper' && dirVar === 'swimshirt') prefixes.push(`clothes/under_upper/swimshirt/${f.dir}`);
        function pushBase(base) { for (const prefix of prefixes) addGrayVariants(out, prefix + base + ext); }

        // Handheld has a different state vocabulary in 0.5.8.
        if (slot === 'handheld') {
            let m = core.match(/^(left|right)-(idle|hold|cover)(.*?)(-acc)?$/);
            if (m) {
                const side = m[1];
                const state = m[2];
                const rest = (m[3] || '').replace(/-/g, '_');
                const acc = m[4] ? '_acc' : '';
                if (HANDHELD_ARM_DIRS.has(dirVar)) {
                    let old = state === 'cover' ? `${side}_cover${rest}${acc}` : `${side}${rest}${acc}`;
                    pushBase(old);
                } else if (HANDHELD_ACC_SWAP_DIRS.has(dirVar) && side === 'right' && m[4]) {
                    if (state === 'cover') pushBase('right_acc');
                    if (state === 'hold') pushBase('right_cover_acc');
                } else {
                    const swap = HANDHELD_SWAP_DIRS.has(dirVar);
                    let coverFlag = (state === (swap ? 'hold' : 'cover')) ? '_cover' : '';
                    pushBase(`${side}${coverFlag}${rest}${acc}`);
                }
            }
        }

        // Generic arm states outside handheld.
        let a = core.match(/^(left|right)-(idle|cover|hold)(.*?)(-acc)?$/);
        if (a && slot !== 'handheld') {
            const side = a[1], state = a[2];
            const rest = (a[3] || '').replace(/-/g, '_');
            const acc = a[4] ? '_acc' : '';
            if (state === 'idle') pushBase(`${side}${rest}${acc}`);
            else if (state === 'cover') pushBase(`${side}_cover${rest}${acc}`);
            else if (state === 'hold' && side === 'right') pushBase(`hold${rest}${acc}`);
        }

        // Rosesuit/witchprisoner exceptions lack an idle state in modern names.
        let r = core.match(/^(left|right)-(shirt|arm)(-alt)?$/);
        if (r) pushBase(`${r[1]}_${r[2]}${r[3] ? '_alt' : ''}`);

        // Common filename folding. This is a candidate only; native request is still tried first.
        pushBase(core.replace(/-/g, '_'));
        // Generic legacy version omitted explicit idle/primary state segments in many clothes assets.
        pushBase(core.replace(/-idle/g, '').replace(/-primary/g, '').replace(/-/g, '_'));

        return out;
    }

    /**
     * UI 官方歷史命名候選。
     * 無法規則化的語義改名走 EXACT；coin / star 等規律名稱在此生成。
     */
    function uiCandidates(path) {
        const out = [];
        if (!path.startsWith('ui/')) return out;
        const exact = EXACT.get(path);
        if (exact) out.push(exact);
        const f = splitFile(path);
        let m;
        if ((m = f.base.match(/^coin-(copper|gold|silver|platinum|jeweled)(?:-(fake|dull))?$/))) {
            const cap = m[1][0].toUpperCase() + m[1].slice(1);
            const suf = m[2] ? m[2][0].toUpperCase() + m[2].slice(1) : '';
            out.push(`${f.dir}${cap}Coin${suf}${f.ext}`);
        }
        if ((m = f.base.match(/^star-(gold|bronze|silver|empty)$/))) out.push(`${f.dir}${m[1]}_star${f.ext}`);
        return out;
    }

    /*
     * ============================================================
     * Extra / Third-party Compatibility Rules
     * ============================================================
     *
     * 這些規則不是用來取代舊版 SPECIAL_RENAMES 的官方映射，
     * 而是後來額外加入、需要保留自身語義與優先級的兼容規則。
     *
     * mode:
     *   "before-native"  - 先嘗試特殊資源，再嘗試官方 Modern 資源。
     *                      用於「Modern 官方原圖一定存在，但希望美化圖優先」的情況。
     *
     *   "after-native"   - Modern MISS 後才嘗試。
     *                      用於第三方不同命名方式之間的普通 fallback。
     *
     * 新增特殊兼容時優先往這裡加，不要再塞進官方 Candidate Generator。
     */
    const EXTRA_COMPAT_RULES = [
        {
            name: 'cow-ears-spotted-legacy-beauty',
            mode: 'before-native',
            match(path) {
                return /^transformations\/cow\/ears\/spotted-[^/]+\.png$/i.test(path);
            },
            candidates(path) {
                const f = splitFile(path);
                return [f.dir + f.base.replace(/-/g, ' ') + f.ext];
            }
        },
        {
            name: 'face-blush-variant',
            mode: 'after-native',
            match(path) {
                return path.startsWith('face/') && /\/blush-?\d+\.png$/i.test(path);
            },
            candidates(path) {
                const out = [];
                let m = path.match(/^(.*\/)?blush-(\d+)\.png$/i);
                if (m) out.push(`${m[1] || ''}blush${m[2]}.png`);
                m = path.match(/^(.*\/)?blush(\d+)\.png$/i);
                if (m) out.push(`${m[1] || ''}blush-${m[2]}.png`);
                return out;
            }
        },
        {
            name: 'face-tear-variant',
            mode: 'after-native',
            match(path) {
                return path.startsWith('face/') && /\/(?:tear-?\d+|tears-\d+)\.png$/i.test(path);
            },
            candidates(path) {
                const out = [];
                let m = path.match(/^(.*\/)?tears-(\d+)\.png$/i);
                if (m) {
                    out.push(
                        `${m[1] || ''}tear${m[2]}.png`,
                        `${m[1] || ''}tear-${m[2]}.png`
                    );
                }
                m = path.match(/^(.*\/)?tear-?(\d+)\.png$/i);
                if (m) {
                    out.push(
                        `${m[1] || ''}tears-${m[2]}.png`,
                        `${m[1] || ''}tear${m[2]}.png`
                    );
                }
                return out;
            }
        },
        {
            name: 'face-mouth-orgasm-default',
            mode: 'after-native',
            match(path) {
                return /^face\/[^/]+\/[^/]+\/mouth-orgasm\.png$/i.test(path)
                    && !/^face\/default\/default\/mouth-orgasm\.png$/i.test(path);
            },
            candidates(path) {
                return ['face/default/default/mouth-orgasm.png'];
            }
        }
    ];

    /**
     * 生成指定 mode 的特殊候選，並保留規則來源供 Debug 使用。
     * 同一路徑若由多條特殊規則產生，只 probe 一次。
     */
    function generateExtraCandidateDetails(key, mode) {
        const records = new Map();

        for (const rule of EXTRA_COMPAT_RULES) {
            if (rule.mode !== mode || !rule.match(key)) continue;

            for (const path of rule.candidates(key) || []) {
                if (!path || path === key) continue;
                if (!records.has(path)) records.set(path, { path, rules: [], special: true, mode });
                const rec = records.get(path);
                if (!rec.rules.includes(rule.name)) rec.rules.push(rule.name);
            }
        }

        return [...records.values()];
    }

    /*
     * ============================================================
     * Candidate Provenance / Debug Metadata
     * ============================================================
     */

    /**
     * 為官方 Candidate 標記規則來源。Runtime 不依賴此 label，
     * 只用於 Debug 解釋候選是由哪類規則生成。
     */
    function candidateRuleLabel(key, candidate, group) {
        if (group === 'exact') return 'exact-exception';
        if (group === 'clothes') {
            if (/_gray\.png$/i.test(candidate) && !/_gray\.png$/i.test(key)) {
                return 'clothes:legacy-name+gray';
            }
            return 'clothes:legacy-name';
        }
        if (group === 'body') return 'body:legacy-name';
        if (group === 'bodywriting') return 'bodywriting:legacy-name';
        if (group === 'ui') return 'ui:legacy-name';
        return group;
    }

    /**
     * 聚合所有「官方」Legacy Candidates。
     *
     * 注意：這裡刻意不包含 EXTRA_COMPAT_RULES，兩者分開是為了保留
     * before-native / after-native 等不同執行語義。
     *
     * Generate official legacy fallback candidates together with provenance information.
     *
     * Runtime resolution still consumes only candidate paths; the extra rule list
     * exists solely for debugging so a failed request can explain *why* each
     * candidate was generated.
     */
    function generateLegacyCandidateDetails(key) {
        const records = new Map();

        function add(path, group) {
            if (!path || path === key || /_gray_gray(?:\.png|_)/i.test(path)) return;
            const rule = candidateRuleLabel(key, path, group);
            if (!records.has(path)) records.set(path, { path, rules: [] });
            const rec = records.get(path);
            if (!rec.rules.includes(rule)) rec.rules.push(rule);
        }

        if (EXACT.has(key)) add(EXACT.get(key), 'exact');
        for (const path of bodyCandidates(key)) add(path, 'body');
        for (const path of bodywritingCandidates(key)) add(path, 'bodywriting');
        for (const path of clothesCandidates(key)) add(path, 'clothes');
        for (const path of uiCandidates(key)) add(path, 'ui');

        return [...records.values()];
    }

    /** Runtime 精簡接口：只回傳 candidate path。 */
    function generateLegacyCandidates(key) {
        return generateLegacyCandidateDetails(key).map(x => x.path);
    }


    /**
     * Legacy clothes 的 *_gray.png 是可供 Renderer 染色的舊版素材。
     * 若 Modern request 本身不是 gray，這類候選需要在 Native Modern 前 probe，
     * 否則 Native 一旦存在，就永遠沒有機會採用舊版可染色素材。
     *
     * 只提升 clothes/ 下由官方 Candidate Generator 產生的 gray；
     * 其他目錄與普通 Legacy 候選仍維持 Native Modern 優先。
     */
    function generatePreferredLegacyGrayDetails(key, officialDetails = null) {
        if (!key.startsWith('clothes/') || /_gray\.png$/i.test(key)) return [];

        const details = officialDetails || generateLegacyCandidateDetails(key);
        return details.filter(rec => /_gray\.png$/i.test(rec.path));
    }

    /*
     * ============================================================
     * Runtime Resolver
     * ============================================================
     */

    function startHook() {
        if (!window.modImgLoaderHooker || !window.modImgLoaderHooker.addSideHooker) {
            setTimeout(startHook, 100);
            return;
        }

        /*
         * successCache：已成功載入並轉成 Base64 的圖片，採 LRU 淘汰。
         * failureCache：短期負快取；連續失敗會退避，但紀錄最終會過期。
         * pendingCache：同一路徑正在載入時共用 Promise，避免重複 probe。
         * probingSet：本模組正在主動 probe 的路徑，用來避免 new Image()
         *             再次觸發自己的 Hook 造成遞迴。
         * requestHistory：聚合 Debug 結果與 repeat 次數。
         */
        const SUCCESS_CACHE_LIMIT = 1000;
        const FAILURE_CACHE_LIMIT = 1000;
        const FAILURE_RETRY_DELAYS = [3000, 10000, 30000];
        const FAILURE_EXPIRE_TTL = 5 * 60 * 1000;

        const successCache = new Map();
        const failureCache = new Map();
        const pendingCache = new Map();
        const probingSet = new Set();
        const requestHistory = new Map();

        /** LRU HIT：命中後移到 Map 尾端，避免常用圖片被淘汰。 */
        function getSuccessCache(key) {
            if (!successCache.has(key)) return null;
            const value = successCache.get(key);
            successCache.delete(key);
            successCache.set(key, value);
            return value;
        }

        /** LRU SET：超過容量時只淘汰最久未使用的一筆，不再整包 clear。 */
        function setSuccessCache(key, value) {
            if (successCache.has(key)) successCache.delete(key);
            successCache.set(key, value);
            while (successCache.size > SUCCESS_CACHE_LIMIT) {
                const oldestKey = successCache.keys().next().value;
                successCache.delete(oldestKey);
            }
        }

        /**
         * 回傳負快取是否仍在冷卻期。
         * expiresAt 到期後整筆刪除，連續失敗次數也會重置。
         */
        function isFailureCoolingDown(key) {
            const entry = failureCache.get(key);
            if (!entry) return false;

            const now = Date.now();
            if (now >= entry.expiresAt) {
                failureCache.delete(key);
                return false;
            }

            // 被讀取過的紀錄移到尾端，容量淘汰時優先清理更久未使用的項目。
            failureCache.delete(key);
            failureCache.set(key, entry);
            return now < entry.retryAfter;
        }

        /** 記錄一次 MISS，採 3s → 10s → 30s 的退避，並限制負快取容量。 */
        function recordFailure(key) {
            const now = Date.now();
            const old = failureCache.get(key);
            const attempts = (!old || now >= old.expiresAt) ? 1 : old.attempts + 1;
            const delay = FAILURE_RETRY_DELAYS[Math.min(attempts - 1, FAILURE_RETRY_DELAYS.length - 1)];

            if (failureCache.has(key)) failureCache.delete(key);
            failureCache.set(key, {
                attempts,
                retryAfter: now + delay,
                expiresAt: now + FAILURE_EXPIRE_TTL
            });

            while (failureCache.size > FAILURE_CACHE_LIMIT) {
                const oldestKey = failureCache.keys().next().value;
                failureCache.delete(oldestKey);
            }
        }

        function clearFailure(key) {
            failureCache.delete(key);
        }

        /* ======================== Debug Trace ======================== */

        function getDebugMode() {
            const mode = window.setup && setup.LegacyArtCompatDebugMode;
            return ['all', 'fail-only', 'hit-only', 'off'].includes(mode) ? mode : 'all';
        }

        function shouldPrintTrace(trace) {
            const mode = getDebugMode();
            if (!DEBUG || mode === 'off') return false;
            if (mode === 'fail-only') return trace.outcome === 'FAIL';
            if (mode === 'hit-only') return trace.outcome === 'NATIVE' || trace.outcome === 'FALLBACK' || trace.outcome === 'OVERRIDE';
            return true;
        }

        /** 產生結果簽名，用於相同 Request 結果去重。 */
        function traceSignature(trace) {
            return [trace.outcome, trace.resolved || '', trace.attempts.map(x => `${x.phase || 'fallback'}:${x.path}:${x.result}`).join('|')].join('::');
        }

        /**
         * 一次 Request 完成後統一輸出完整 Trace。
         * outcome：NATIVE / OVERRIDE / FALLBACK / FAIL。
         */
        function emitTrace(trace) {
            const sig = traceSignature(trace);
            const prev = requestHistory.get(trace.original);
            if (prev && prev.signature === sig) {
                prev.count++;
                prev.lastTime = performance.now();
                return;
            }

            requestHistory.set(trace.original, {
                signature: sig,
                count: 1,
                lastTime: performance.now(),
                outcome: trace.outcome,
                resolved: trace.resolved || null,
                attempts: trace.attempts.length
            });

            if (!shouldPrintTrace(trace)) return;

            const title = `[${TARGET_MOD}][${trace.outcome}] ${trace.original}`;
            const group = console.groupCollapsed || console.group;
            if (typeof group === 'function') group.call(console, title);
            else console.log(title);

            console.log('original:', trace.original);
            if (trace.native) {
                console.log(`native: ${trace.native.result}${trace.native.source ? ` (${trace.native.source})` : ''}`);
            } else {
                console.log('native: NOT TRIED');
            }

            trace.attempts.forEach((attempt, i) => {
                console.log(
                    `[${i + 1}/${trace.attempts.length}] ${attempt.result}`,
                    attempt.path,
                    `phase=${attempt.phase || 'fallback'}`,
                    `rule=${attempt.rules.join('+')}`,
                    attempt.source ? `source=${attempt.source}` : ''
                );
            });

            if (trace.outcome === 'NATIVE') {
                console.log('final: NATIVE HIT');
            } else if (trace.outcome === 'OVERRIDE') {
                console.log('final: SPECIAL OVERRIDE HIT ->', trace.resolved);
            } else if (trace.outcome === 'FALLBACK') {
                console.log('final: FALLBACK HIT ->', trace.resolved);
            } else {
                console.log(`final: FAIL (tried ${trace.attempts.length} legacy candidates)`);
            }

            if (typeof console.groupEnd === 'function') console.groupEnd();
        }

        /**
         * 直接載入一條具體圖片路徑並轉成 Base64。
         * 同時使用 success / failure cache，並透過 probingSet 防止 Hook 遞迴。
         */
        async function loadAndConvertToBase64(relativePath) {
            if (!relativePath) return { data: null, result: 'MISS', source: 'invalid' };

            const guessPath = relativePath.startsWith('img/') ? relativePath : 'img/' + relativePath;
            const cleanedGuess = cleanPath(guessPath);

            const cached = getSuccessCache(cleanedGuess);
            if (cached !== null) {
                return { data: cached, result: 'HIT', source: 'cache' };
            }

            if (isFailureCoolingDown(cleanedGuess)) {
                return { data: null, result: 'MISS', source: 'failure-cache' };
            }

            // 同一路徑已經在載入時，直接等待同一個 Promise。
            if (pendingCache.has(cleanedGuess)) {
                return pendingCache.get(cleanedGuess);
            }

            const pending = new Promise(resolve => {
                probingSet.add(cleanedGuess);

                const img = new Image();
                img.crossOrigin = 'Anonymous';

                img.onload = () => {
                    probingSet.delete(cleanedGuess);

                    try {
                        const canvas = document.createElement('canvas');
                        canvas.width = img.width;
                        canvas.height = img.height;
                        canvas.getContext('2d').drawImage(img, 0, 0);

                        const b64 = canvas.toDataURL('image/png');
                        setSuccessCache(cleanedGuess, b64);
                        clearFailure(cleanedGuess);

                        resolve({ data: b64, result: 'HIT', source: 'load' });
                    } catch (e) {
                        recordFailure(cleanedGuess);
                        resolve({ data: null, result: 'MISS', source: 'convert-error' });
                    }
                };

                img.onerror = () => {
                    probingSet.delete(cleanedGuess);
                    recordFailure(cleanedGuess);
                    resolve({ data: null, result: 'MISS', source: 'load' });
                };

                img.src = guessPath;
            });

            pendingCache.set(cleanedGuess, pending);

            try {
                return await pending;
            } finally {
                // 只刪除自己建立的 Promise，避免極端情況誤刪後來的新請求。
                if (pendingCache.get(cleanedGuess) === pending) {
                    pendingCache.delete(cleanedGuess);
                }
            }
        }

        /* ===================== Console Debug APIs ===================== */

        window.LegacyArtCompatGenerateCandidates = function (src) {
            return generateLegacyCandidates(cleanPath(src));
        };

        window.LegacyArtCompatGenerateCandidateDetails = function (src) {
            return generateLegacyCandidateDetails(cleanPath(src));
        };

        window.LegacyArtCompatGenerateSpecialCandidateDetails = function (src) {
            const key = cleanPath(src);
            return {
                beforeNative: generateExtraCandidateDetails(key, 'before-native'),
                afterNative: generateExtraCandidateDetails(key, 'after-native')
            };
        };

        window.LegacyArtCompatDebugSummary = function () {
            const rows = [...requestHistory.entries()].map(([path, info]) => ({
                path,
                outcome: info.outcome,
                resolved: info.resolved,
                attempts: info.attempts,
                repeats: info.count
            }));
            console.table(rows);
            return rows;
        };

        window.LegacyArtCompatClearDebugHistory = function () {
            requestHistory.clear();
            console.log(`[${TARGET_MOD}] debug history cleared`);
        };

        // Delay renderer invalidation until the current fallback/imageGetter cycle
        // has returned. Multiple fallback loads are debounced into one refresh.
        let rendererRefreshTimer = null;

        function scheduleRendererRefresh() {
            if (rendererRefreshTimer !== null) return;

            rendererRefreshTimer = setTimeout(() => {
                rendererRefreshTimer = null;
                const R = window.Renderer;
                if (!R) return;

                try {
                    if (R.Stats?.logmsgLoad) R.Stats.logmsgLoad.value = "";
                    if (R.Stats?.logmsgRender) R.Stats.logmsgRender.value = "";
                    if (R.Stats?.logmsgAnimate) R.Stats.logmsgAnimate.value = "";
                    R.ImageCaches = {};
                    R.ImageErrors = {};
                    R.lastAnimation?.invalidateCaches?.();
                    if (R.lastModel?.layerList) {
                        R.invalidateLayerCaches?.(R.lastModel.layerList);
                    }
                    R.lastModel?.redraw?.();
                    console.log(`[${TARGET_MOD}][CACHE] deferred fallback refresh -> Renderer caches refreshed and redrawn (50ms debounce)`);
                } catch (err) {
                    console.warn(`[${TARGET_MOD}][CACHE] deferred Renderer refresh failed:`, err);
                }
            }, 50);
        }

        /*
         * ========================================================
         * ImageLoader Side Hook
         * ========================================================
         *
         * 執行順序：
         *   Phase 0    before-native 特殊規則
         *   Phase 0.5  Legacy clothes gray
         *   Phase 1    Native Modern
         *   Phase 2    after-native 特殊規則
         *   Phase 3    其餘官方 Legacy Candidates
         * ========================================================
         */
        window.modImgLoaderHooker.addSideHooker({
            hookName: TARGET_MOD + '_CandidateResolver',
            /**
             * 只有能產生官方候選或特殊候選時，本模組才宣告介入。
             * probingSet 中的路徑是本模組自己的 probe，必須略過以防遞迴。
             */
            checkImageExist(src) {
                const key = cleanPath(src);
                if (probingSet.has(key)) return undefined;

                const hasOfficial = generateLegacyCandidates(key).length > 0;
                const hasSpecial =
                    generateExtraCandidateDetails(key, 'before-native').length > 0 ||
                    generateExtraCandidateDetails(key, 'after-native').length > 0;

                return (hasOfficial || hasSpecial) ? true : undefined;
            },
            /**
             * 真正的 Request resolver。
             * 官方大映射表的重構結果只放在 Phase 3；第三方/特殊語義則保持
             * 獨立規則與自己的執行優先級。
             */
            async imageGetter(src) {
                const key = cleanPath(src);
                if (probingSet.has(key)) return undefined;

                // 官方大映射表重構後的候選。
                const officialDetails = generateLegacyCandidateDetails(key);

                // clothes 的 Legacy gray 是可染色素材，需要在 Native 前單獨提升優先級。
                const preferredLegacyGray = generatePreferredLegacyGrayDetails(key, officialDetails);
                const preferredLegacyGrayPaths = new Set(preferredLegacyGray.map(rec => rec.path));

                // 額外擴展規則保留自身優先級，不混進官方 Candidate Generator。
                const beforeNative = generateExtraCandidateDetails(key, 'before-native');
                const afterNative = generateExtraCandidateDetails(key, 'after-native');

                if (!officialDetails.length && !beforeNative.length && !afterNative.length) {
                    return undefined;
                }

                const trace = {
                    original: key,
                    native: null,
                    attempts: [],
                    outcome: 'FAIL',
                    resolved: null
                };

                // Phase 0: 特殊優先規則。
                // 例如牛耳：Modern 官方原圖本來就存在，若先試 native 就永遠吃不到舊美化圖。
                for (const rec of beforeNative) {
                    const mapped = await loadAndConvertToBase64(rec.path);
                    trace.attempts.push({
                        path: rec.path,
                        rules: rec.rules,
                        phase: 'before-native',
                        result: mapped.result,
                        source: mapped.source
                    });
                    if (mapped.data) {
                        trace.outcome = 'OVERRIDE';
                        trace.resolved = rec.path;
                        emitTrace(trace);
                        return mapped.data;
                    }
                }

                // Phase 0.5: Legacy clothes gray 優先。
                // 這些是舊版可染色素材；若存在，應優先於新版 non-gray Native。
                for (const rec of preferredLegacyGray) {
                    const mapped = await loadAndConvertToBase64(rec.path);
                    trace.attempts.push({
                        path: rec.path,
                        rules: rec.rules,
                        phase: 'legacy-gray-before-native',
                        result: mapped.result,
                        source: mapped.source
                    });
                    if (mapped.data) {
                        trace.outcome = 'OVERRIDE';
                        trace.resolved = rec.path;
                        emitTrace(trace);

                        if (mapped.source === 'load') {
                            scheduleRendererRefresh();
                        }

                        return mapped.data;
                    }
                }

                // Phase 1: Native Modern wins over all remaining ordinary fallback rules.
                const native = await loadAndConvertToBase64(key);
                trace.native = { result: native.result, source: native.source };
                if (native.data) {
                    trace.outcome = 'NATIVE';
                    trace.resolved = key;
                    emitTrace(trace);
                    return native.data;
                }

                // Phase 2: 額外第三方 fallback（例如 AU 面擴多版本命名）。
                for (const rec of afterNative) {
                    const mapped = await loadAndConvertToBase64(rec.path);
                    trace.attempts.push({
                        path: rec.path,
                        rules: rec.rules,
                        phase: 'special-fallback',
                        result: mapped.result,
                        source: mapped.source
                    });
                    if (mapped.data) {
                        trace.outcome = 'FALLBACK';
                        trace.resolved = rec.path;
                        emitTrace(trace);

                        // A fallback that had to be loaded may have arrived after the
                        // current render already cached the image/layer as unavailable.
                        // Reproduce the game's image-cache refresh/redraw path once here.
                        // Cache HITs must not trigger this repeatedly on later frames.
                        if (mapped.source === 'load') {
                            scheduleRendererRefresh();
                        }

                        return mapped.data;
                    }
                }

                // Phase 3: 其餘官方新舊版本路徑 Candidate Generator。
                // Phase 0.5 已 probe 過的 gray 不再重複處理。
                for (const rec of officialDetails) {
                    if (preferredLegacyGrayPaths.has(rec.path)) continue;

                    const mapped = await loadAndConvertToBase64(rec.path);
                    trace.attempts.push({
                        path: rec.path,
                        rules: rec.rules,
                        phase: 'official-fallback',
                        result: mapped.result,
                        source: mapped.source
                    });
                    if (mapped.data) {
                        trace.outcome = 'FALLBACK';
                        trace.resolved = rec.path;
                        emitTrace(trace);

                        // A fallback that had to be loaded may have arrived after the
                        // current render already cached the image/layer as unavailable.
                        // Reproduce the game's image-cache refresh/redraw path once here.
                        // Cache HITs must not trigger this repeatedly on later frames.
                        if (mapped.source === 'load') {
                            scheduleRendererRefresh();
                        }

                        return mapped.data;
                    }
                }

                emitTrace(trace);
                return undefined;
            },
            /** 本模組只做 side-hook resolver，不接管 ImageLoader 主流程。 */
            async imageLoader() { return false; }
        });

        console.log(`✅ [${TARGET_MOD}] 候选式官方映射 + 独立扩展规则已启用（聚合调试日志）`);
    }

    // 初次短延遲啟動；startHook 內部會持續等待 ImageLoaderHooker。
    setTimeout(startHook, 50);
})();

/*
 * ==============================================================
 * Legacy Clothes "covered" Trait Compatibility
 * ==============================================================
 *
 * 這部分與圖片路徑 Candidate Generator 無關。
 *
 * 舊版 type: ["covered"] 在新版依 slot 拆成：
 *   under_upper → torso_covering
 *   under_lower → lower_covering
 *   lower       → overalls
 *   face        → face_covering
 *
 * 因此同時處理：
 * 1. 之後經 updateClothesItem() 更新的服裝
 * 2. storyready 時已存在於 setup.clothes 的服裝
 * ==============================================================
 */

$(document).one(":storyready", function () {

    // 動態服裝資料：包裝 updateClothesItem，先正規化 legacy covered trait。
    if (typeof window.updateClothesItem === "function") {
        const _originalUpdateClothesItem = window.updateClothesItem;

        window.updateClothesItem = function (slot, item, debug) {
            if (item && item.type && item.type.includes("covered")) {
                const currentSlot = item.slot || slot;
                const idx = item.type.indexOf("covered");

                if (idx !== -1) {
                    let targetType = "";

                    switch (currentSlot) {
                        case "under_upper": targetType = "torso_covering"; break;
                        case "under_lower": targetType = "lower_covering"; break;
                        case "lower":       targetType = "overalls"; break;
                        case "face":        targetType = "face_covering"; break;
                    }

                    if (targetType) {
                        item.type.splice(idx, 1, targetType);
                    } else {
                        item.type.splice(idx, 1);
                    }
                }
            }

            return _originalUpdateClothesItem.apply(this, arguments);
        };
    }

    // 初始化時已存在的服裝資料：storyready 時再掃一次 setup.clothes。
    if (setup && setup.clothes) {
        for (const slot in setup.clothes) {
            if (!Array.isArray(setup.clothes[slot])) continue;

            setup.clothes[slot].forEach(item => {
                if (item && item.type && item.type.includes("covered")) {
                    const idx = item.type.indexOf("covered");

                    if (idx !== -1) {
                        let targetType = "";

                        switch (slot) {
                            case "under_upper": targetType = "torso_covering"; break;
                            case "under_lower": targetType = "lower_covering"; break;
                            case "lower":       targetType = "overalls"; break;
                            case "face":        targetType = "face_covering"; break;
                        }

                        if (targetType) {
                            item.type.splice(idx, 1, targetType);
                        } else {
                            item.type.splice(idx, 1);
                        }
                    }
                }
            });
        }
    }

});